### ISSUE TITLE
[urgent] Am I mistaken or is this broken right now?

### ISSUE THREAD

**Issue by mcookhome** [guoguo12/billboard-charts#35]
I have tried to retrieve a chart on two separate machines, and have been unable to get any tracks:

![broken billboard](https://user-images.githubusercontent.com/5422547/42801495-cff726fe-896d-11e8-8a5e-51437692253c.png)

Am I calling it wrong @guoguo12?

I notice that Billboard's website's UI has changed, and fairly drastically so.  I imagine that could have easily messed up the fairly advanced scraping you're doing. 

If there's any more context I could give to help, please let me know.

**Comment by guoguo12** [comment]
Yup, looks very much broken. They changed the UI sometime in the past 20 hours.

I can't work on this at the moment, but perhaps someone else can take a look. 

Thanks for reporting this!

**Comment by mcookhome** [comment]
Thanks for the super-quick response. Do you think this is reparable? Would you be able to work on it within the next week? I'm willing to help, but you would definitely be able to fix it much more quickly. 

Again, thanks for the quick response, and sorry to ask you to work on it, but I've really enjoyed using this module and would like to continue doing so.

**Comment by guoguo12** [comment]
I'm overseas without a laptop until the 25th. :slightly_frowning_face:

**Comment by mcookhome** [comment]
Darn, that's pretty awesome though. Hope you're having fun.

Would you be opposed to me working on a fix in the meantime? If not, do you have any tips/recommendations on how to tackle this? Would you be able to look at a pull request while overseas?

Enjoy your trip!

**Comment by guoguo12** [comment]
> Would you be opposed to me working on a fix in the meantime?

Of course not! I would be very grateful if you did that. 

> If not, do you have any tips/recommendations on how to tackle this?

The logic for parsing the HTML is pretty straightforward. Ugly, even. Fixing the logic will mostly involve looking at the new HTML, updating the scraping code, and testing.

Oh, and there's already unit tests written, so you'll know when you have it correct. :) 

> Would you be able to look at a pull request while overseas?

Probably!

**Comment by mcookhome** [comment]
Awesome! again, thanks for the super quick response. Expect more questions as I work on it and a pull request soon!

**Comment by mcookhome** [comment]
thanks @danielunderwood!

I actually submitted and merged [a PR](https://github.com/guoguo12/billboard-charts/pull/36) yesterday! Allen merged and deployed to PyPI, so some features should be moderately back to normal (buggy, but somewhat functional instead of not at all).

The artist charts are definitely not working. If you find any other issues while using the application, definitely keep me posted! I've been finding some already.

**Comment by danielunderwood** [comment]
Ahh I missed that PR. Looks like albums are working for me, though the artist-100 chart does fail with
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "billboard.py", line 135, in __init__
    self.fetchEntries()
  File "billboard.py", line 207, in fetchEntries
    raise BillboardParseException(message)
BillboardParseException: Failed to parse top track artist
```

and artist-50 fails with
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "billboard.py", line 135, in __init__
    self.fetchEntries()
  File "billboard.py", line 197, in fetchEntries
    raise BillboardParseException(message)
BillboardParseException: Failed to parse top track title
```

**Comment by afriedman412** [comment]
thanks to everyone who's working on this!

**Comment by mcookhome** [comment]
which chart? is it songs or artists?

which date? 

what error are you getting? I would say what are are you getting, if any, but I'm pretty sure you should be getting an error

**Comment by afriedman412** [comment]
it's the R&B/Hip-Hop Albums chart

mostly calling it in this function:
```
def charto(chart='r-b-hip-hop-albums', date='1984-01-22'):
    return billboard.ChartData(chart, date)
```
and it's returning absolutely nothing, just the "r-b-hip-hop-albums chart from 1984-01-22" header with nothing under it

**Comment by guoguo12** [comment]
Just pushed version 4.4.2 to PyPI.

I think the major breakdowns caused by the UI change have now all been resolved. Thanks again to @mcookhome and @johannfrias.

I expect many more minor bugs to be found in the coming weeks.

This UI change revealed several notable gaps in test coverage:
* We have no tests involving albums charts.
* We have no test for when a non-existent chart name is used: `billboard.ChartData('nonsense')`. We don't even have a specified behavior for this case.
* We had (until 8a46ef083380f481f15f46f7b53f6af95f4a9025) no tests for `previousDate` and `nextDate`.
* We need more tests involving date edge cases (earliest chart, most recent chart, etc.).

I will make a new issue for these.

**Comment by guoguo12** [comment]
@afriedman412: Your problem with the R&B/Hip-Hop Albums chart should be resolved.

**Comment by ProfoundWanderer** [comment]
![screen shot 2018-07-25 at 9 16 57 am](https://user-images.githubusercontent.com/18703678/43206679-e8caa7f8-8feb-11e8-82e6-a38fad4cb4a0.png)
Is this still an issue going on or am I missing something? I am using version 4.4.2

 Also let me know if this is the wrong place to ask, I am still new to commenting on github.

**Comment by mcookhome** [comment]
Update: I typed `'top-100'` instead of `'hot-100'` and got the above error. However, when I do `'hot-100'` it works. So I am not able to reproduce. I do think we should have better error handling on the chart titles soon, though.

[Here's a Pyfiddle](https://pyfiddle.io/fiddle/93d9411c-f289-4e5a-bad0-8170ac772ea8/?i=true) showing it working @ProfoundWanderer. can you try it again please?

**Comment by ProfoundWanderer** [comment]
![screen shot 2018-07-25 at 9 36 13 am](https://user-images.githubusercontent.com/18703678/43207678-345199d2-8fee-11e8-98d6-1f7111e6a62b.png)
@mcookhome I am still getting the same issue but it may be this machine so I am going to try a different one when I go home and report back.

**Comment by mcookhome** [comment]
that would be helpful. I'm not in a great place to test right now, so I appreciate it. Sorry for the inconvenience: everything is in a state of flux right now because Billboard just changed their UI about a week ago.

**Comment by ProfoundWanderer** [comment]
@mcookhome I worked at home on my personal computer using pycharm but at work using pythonanywhere it gets the error I mentioned before so I believe the issue is with pythonanywhere not sure why though. I will just run it from my computer from here on out.
